// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab44.Data;

namespace lab44.Migrations
{
    [DbContext(typeof(lab44Context))]
    [Migration("20210429192356_base_2")]
    partial class base_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lab44.modele.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAZWA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NRREJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUCENT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("lab44.modele.Kierowca", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IMIE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAZWISKO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLEC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WIEK")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Kierowca");
                });

            modelBuilder.Entity("lab44.modele.Telefon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAZWA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NRTEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUCENT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Telefon");
                });

            modelBuilder.Entity("lab44.modele.Zmiana", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KIEROWCAID")
                        .HasColumnType("int");

                    b.Property<int?>("SAMOCHODID")
                        .HasColumnType("int");

                    b.Property<int?>("TELEFONID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KIEROWCAID");

                    b.HasIndex("SAMOCHODID");

                    b.HasIndex("TELEFONID");

                    b.ToTable("Zmiana");
                });

            modelBuilder.Entity("lab44.modele.Zmiana", b =>
                {
                    b.HasOne("lab44.modele.Kierowca", "KIEROWCA")
                        .WithMany()
                        .HasForeignKey("KIEROWCAID");

                    b.HasOne("lab44.modele.Car", "SAMOCHOD")
                        .WithMany()
                        .HasForeignKey("SAMOCHODID");

                    b.HasOne("lab44.modele.Telefon", "TELEFON")
                        .WithMany()
                        .HasForeignKey("TELEFONID");

                    b.Navigation("KIEROWCA");

                    b.Navigation("SAMOCHOD");

                    b.Navigation("TELEFON");
                });
#pragma warning restore 612, 618
        }
    }
}
